name: exf
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: '>=2.18.5 <3.0.0'

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter
    


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  http: ^0.13.5
  google_fonts: ^3.0.1
  data_connection_checker: ^0.3.4
  flutter_splash_screen: ^1.0.0+6
  animated_splash_screen: ^1.3.0
  animated_image_list: ^1.0.0
  animated_text_kit: ^4.2.2
  updater: ^0.1.5
  upgrader: ^5.1.0
  

dev_dependencies: 
  flutter_test:
    sdk: flutter
  splashscreen: ^1.3.5
  connectivity_plus: ^2.2.1
  flutter_launcher_icons_maker: "^0.10.1"

flutter_icons:
  android: true
  ios: true
  macos: true
  windows: true
  web: true
  image_path: "assets/cover/images/icon.png"



  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/cover/images/ellipse-4-bg.png
    - assets/cover/images/rectangle-24.png
    - assets/cover/images/rectangle-18-bg.png
    - assets/cover/images/star-5.png
    - assets/cover/images/logo.png
    - assets/cover/images/Sq-01.jpg
    - assets/cover/images/With moto regular.png
    - assets/cover/images/With moto.png
    - assets/cover/images/debo_logo.png
    - assets/cover/images/star-1.png
    - assets/cover/images/rectangle-14.png
    - assets/cover/images/rectangle-6.png
    - assets/cover/images/star-4.png
    - assets/cover/images/rectangle-34624648-removebg-preview.png
    - assets/cover/images/rectangle-10.png
    - assets/design/images/ellipse-6-bg.png
    - assets/cover/images/star-2.png
    - assets/cover/images/star-5-DgW.png
    - assets/cover/images/star-3.png
    - assets/design/images/mask-group.png
    - assets/design/images/ellipse-4-bg-gZp.png
    - assets/design/images/frame.png
    - assets/design/images/frame-sNA.png
    - assets/cover/images/rectangle-22.png
    - assets/design/images/frame-ymk.png
    - assets/cover/images/ellipse-4-bg-exz.png
    - assets/cover/images/star-5-c18.png
    - assets/cover/images/rectangle-26.png
    - assets/design/images/frame-X5U.png
    - assets/design/images/frame-eC2.png
    - assets/design/images/frame-FgE.png
    - assets/design/images/frame-93p.png
    - assets/design/images/frame-Hfp.png
    - assets/design/images/frame-Rn2.png
    - assets/design/images/mask-group-BmC.png
    - assets/design/images/frame-xGA.png
    - assets/cover/images/star-4-KcW.png
    - assets/design/images/ellipse-3-bg.png
    - assets/design/images/mask-group-Tyc.png
    - assets/design/images/frame-SSE.png
    - assets/cover/images/ellipse-4-bg-dwx.png
    - assets/design/images/frame-XBg.png
    - assets/design/images/ellipse-5-bg.png
    - assets/design/images/frame-2u8.png
    - assets/design/images/frame-oQ6.png
    - assets/cover/images/rectangle-23.png
    - assets/cover/images/image-1-bg.png
    - assets/design/images/frame-AuG.png
    - assets/design/images/frame-tqG.png
    - assets/design/images/frame-rn6.png
    - assets/cover/images/star-4-Dce.png
    - assets/design/images/saly-36.png
    - assets/cover/images/rectangle-27.png
    - assets/design/images/frame-LxA.png
    - assets/design/images/saly-21.png
    - assets/design/images/saly-25.png
    - assets/design/images/saly-10-bg.png
    - assets/design/images/saly-36-x3C.png
    - assets/design/images/saly-20.png
    - assets/design/images/saly-24.png
    - assets/design/images/saly-13.png
    


  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
